import type { ReactNode } from 'react'
import type { Status } from './types'

/** Symbol preview. The SVG is generated by our own backend from DXF geometry
 *  (text is escaped there), so injecting it is safe. */
export function SymbolThumb({ svg, size = 56, className = '' }: { svg: string; size?: number; className?: string }) {
  return (
    <div
      className={`symbol-svg shrink-0 rounded-md border border-slate-200 bg-white p-1 text-slate-800 ${className}`}
      style={{ width: size, height: size }}
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}

const STATUS_STYLE: Record<Status, string> = {
  verified: 'bg-emerald-50 text-emerald-700 ring-emerald-600/20',
  suggested: 'bg-amber-50 text-amber-800 ring-amber-600/25',
  unknown: 'bg-rose-50 text-rose-700 ring-rose-600/20',
  ignored: 'bg-slate-100 text-slate-600 ring-slate-500/20',
}
const STATUS_TEXT: Record<Status, string> = {
  verified: 'Verified',
  suggested: 'Suggested',
  unknown: 'Unknown',
  ignored: 'Not a device',
}

export function StatusBadge({ status }: { status: Status }) {
  return (
    <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ring-1 ring-inset ${STATUS_STYLE[status]}`}>
      {STATUS_TEXT[status]}
    </span>
  )
}

export function Card({ children, className = '' }: { children: ReactNode; className?: string }) {
  return <div className={`rounded-xl border border-slate-200 bg-white shadow-sm ${className}`}>{children}</div>
}

export function Stat({ label, value, tone = 'slate' }: { label: string; value: ReactNode; tone?: 'slate' | 'red' | 'amber' | 'green' | 'blue' }) {
  const tones = {
    slate: 'text-slate-900',
    red: 'text-rose-600',
    amber: 'text-amber-600',
    green: 'text-emerald-600',
    blue: 'text-brand-600',
  }
  return (
    <Card className="px-4 py-3">
      <div className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</div>
      <div className={`mt-1 text-2xl font-semibold tabular-nums ${tones[tone]}`}>{value}</div>
    </Card>
  )
}

export function Button({
  children,
  onClick,
  variant = 'primary',
  disabled,
  type = 'button',
  className = '',
  title,
}: {
  children: ReactNode
  onClick?: () => void
  variant?: 'primary' | 'secondary' | 'danger' | 'ghost' | 'success'
  disabled?: boolean
  type?: 'button' | 'submit'
  className?: string
  title?: string
}) {
  const styles = {
    primary: 'bg-brand-600 text-white hover:bg-brand-700',
    success: 'bg-emerald-600 text-white hover:bg-emerald-700',
    secondary: 'border border-slate-300 bg-white text-slate-700 hover:bg-slate-50',
    danger: 'border border-rose-200 bg-white text-rose-700 hover:bg-rose-50',
    ghost: 'text-slate-600 hover:bg-slate-100',
  }
  return (
    <button
      type={type}
      onClick={onClick}
      disabled={disabled}
      title={title}
      className={`inline-flex items-center justify-center gap-1.5 rounded-md px-3 py-1.5 text-sm font-medium transition disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${className}`}
    >
      {children}
    </button>
  )
}

export function ErrorBox({ message, onClose }: { message: string; onClose?: () => void }) {
  return (
    <div role="alert" className="flex items-start justify-between gap-3 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">
      <span>{message}</span>
      {onClose && (
        <button onClick={onClose} className="text-rose-600 hover:text-rose-800" aria-label="Dismiss">
          ✕
        </button>
      )}
    </div>
  )
}

export function Spinner({ label }: { label?: string }) {
  return (
    <div className="flex items-center gap-2 text-sm text-slate-500">
      <span className="h-4 w-4 animate-spin rounded-full border-2 border-slate-300 border-t-brand-600" />
      {label}
    </div>
  )
}

export function shortBlockName(name: string, max = 60) {
  return name.length > max ? name.slice(0, max - 1) + '…' : name
}
