"""project ai policy

Revision ID: 1378dd58ff7a
Revises: d9cbc6066764
Create Date: 2026-09-15 22:35:24.881900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1378dd58ff7a'
down_revision: Union[str, Sequence[str], None] = 'd9cbc6066764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_policy', sa.String(length=16), server_default='allowed', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('ai_policy')

    # ### end Alembic commands ###
