"""material submittal register

Revision ID: 4d88515623a9
Revises: 5c991b47548a
Create Date: 2026-09-12 08:07:43.922311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d88515623a9'
down_revision: Union[str, Sequence[str], None] = '5c991b47548a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_submittals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('system_code', sa.String(length=16), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('revision', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('not_submitted', 'under_review', 'approved', 'rejected', name='submittalstatus'), nullable=False),
    sa.Column('document_path', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_submittal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submittal_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('by_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submittal_id'], ['project_submittals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_submittal_events')
    op.drop_table('project_submittals')
    # ### end Alembic commands ###
