"""provenance on BOQ lines, project documents, BOQ candidates and snapshots, write versions

Revision ID: 57d4377a3045
Revises: b6e2f4a8c913
Create Date: 2026-09-15 20:31:57.239418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57d4377a3045'
down_revision: Union[str, Sequence[str], None] = 'b6e2f4a8c913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boq_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('base_boq_version', sa.Integer(), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('run_ids', sa.JSON(), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decisions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boq_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boq_candidates_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_boq_candidates_status'), ['status'], unique=False)

    op.create_table('boq_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('boq_version', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boq_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boq_snapshots_project_id'), ['project_id'], unique=False)

    op.create_table('project_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('system_code', sa.String(length=16), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('relative_path', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('printed_pages', sa.JSON(), nullable=True),
    sa.Column('intake_status', sa.String(length=16), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('intake_version', sa.String(length=32), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'role', 'path', name='uq_project_document_path')
    )
    with op.batch_alter_table('project_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_documents_intake_status'), ['intake_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_documents_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_documents_sha256'), ['sha256'], unique=False)

    with op.batch_alter_table('compliance_statements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('project_boq_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin', sa.String(length=16), server_default='legacy', nullable=False))
        batch_op.add_column(sa.Column('extraction_run_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_document_sha256', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('source_page', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_region', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('raw_values', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ocr_confidence', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('parser_version', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('extracted_values', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('edited_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_project_boq_items_extraction_run_id'), ['extraction_run_id'], unique=False)
        batch_op.create_foreign_key('fk_project_boq_items_extraction_run_id', 'extraction_runs', ['extraction_run_id'], ['id'])
        batch_op.create_foreign_key('fk_project_boq_items_edited_by_id', 'users', ['edited_by_id'], ['id'])

    with op.batch_alter_table('project_designs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boq_version', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('details_version', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('details_version')
        batch_op.drop_column('boq_version')

    with op.batch_alter_table('project_designs', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('project_boq_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_boq_items_edited_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_project_boq_items_extraction_run_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_project_boq_items_extraction_run_id'))
        batch_op.drop_column('created_at')
        batch_op.drop_column('edited_at')
        batch_op.drop_column('edited_by_id')
        batch_op.drop_column('extracted_values')
        batch_op.drop_column('parser_version')
        batch_op.drop_column('ocr_confidence')
        batch_op.drop_column('raw_values')
        batch_op.drop_column('source_region')
        batch_op.drop_column('source_page')
        batch_op.drop_column('source_document_sha256')
        batch_op.drop_column('extraction_run_id')
        batch_op.drop_column('origin')

    with op.batch_alter_table('compliance_statements', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('project_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_documents_sha256'))
        batch_op.drop_index(batch_op.f('ix_project_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_documents_intake_status'))

    op.drop_table('project_documents')
    with op.batch_alter_table('boq_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boq_snapshots_project_id'))

    op.drop_table('boq_snapshots')
    with op.batch_alter_table('boq_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boq_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_boq_candidates_project_id'))

    op.drop_table('boq_candidates')
    # ### end Alembic commands ###
