"""baseline

The schema as `Base.metadata.create_all` built it before migrations were
adopted. A database created that way already has these tables; mark it with
`alembic stamp 61c335c3ba25` instead of running this.

Revision ID: 61c335c3ba25
Revises: 
Create Date: 2026-09-11 08:24:24.985880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c335c3ba25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'design_manager', 'design_engineer', 'draftsman', 'viewer', name='roleenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ep_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'archived', name='projectstatus'), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('plot_number', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('consultant', sa.String(length=255), nullable=True),
    sa.Column('contractor', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=64), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('scope_of_work', sa.String(length=64), nullable=True),
    sa.Column('other_information', sa.Text(), nullable=True),
    sa.Column('boq_extracted_at', sa.DateTime(), nullable=True),
    sa.Column('design_engineer_id', sa.Integer(), nullable=True),
    sa.Column('source_folder_path', sa.Text(), nullable=True),
    sa.Column('drf_document_path', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['design_engineer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ep_number', name='uq_projects_ep_number')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_ep_number'), ['ep_number'], unique=False)

    op.create_table('project_boq_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('system_code', sa.String(length=32), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('group_heading', sa.String(length=255), nullable=True),
    sa.Column('catalog_no', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.String(length=32), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_design_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('system_code', sa.String(length=16), nullable=True),
    sa.Column('document_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('method_statement', sa.Boolean(), nullable=False),
    sa.Column('drawing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_systems')
    op.drop_table('project_design_sheets')
    op.drop_table('project_boq_items')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_ep_number'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
