"""boq line building and catalog identity

Revision ID: 79d097c1b0d4
Revises: 57d4377a3045
Create Date: 2026-09-15 21:58:52.442780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d097c1b0d4'
down_revision: Union[str, Sequence[str], None] = '57d4377a3045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_boq_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('building', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('catalog_canonical', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('catalog_match', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_boq_items', schema=None) as batch_op:
        batch_op.drop_column('catalog_match')
        batch_op.drop_column('catalog_canonical')
        batch_op.drop_column('building')

    # ### end Alembic commands ###
