"""submittal reference and reply code

Revision ID: 9485f18f6ff4
Revises: 4d88515623a9
Create Date: 2026-09-12 08:29:39.351012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9485f18f6ff4'
down_revision: Union[str, Sequence[str], None] = '4d88515623a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_submittals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('reply_code', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_submittals', schema=None) as batch_op:
        batch_op.drop_column('reply_code')
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
