"""extraction runs and ai proposals

Revision ID: b42f592e597c
Revises: 9485f18f6ff4
Create Date: 2026-09-13 14:23:39.009043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42f592e597c'
down_revision: Union[str, Sequence[str], None] = '9485f18f6ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('document_path', sa.Text(), nullable=False),
    sa.Column('document_sha256', sa.String(length=64), nullable=True),
    sa.Column('system_code', sa.String(length=16), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('lines_accepted', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.JSON(), nullable=False),
    sa.Column('failure', sa.Text(), nullable=True),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('ai_calls', sa.Integer(), nullable=False),
    sa.Column('ai_cost', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('budget_exhausted', sa.String(length=48), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_runs_project_id'), ['project_id'], unique=False)

    op.create_table('result_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('document_sha256', sa.String(length=64), nullable=False),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('result_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_result_cache_document_sha256'), ['document_sha256'], unique=False)

    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=True),
    sa.Column('reasoning_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=24), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['extraction_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_usage_project_id'), ['project_id'], unique=False)

    op.create_table('extraction_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('region', sa.JSON(), nullable=True),
    sa.Column('target', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('state_reason', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['extraction_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_issues_run_id'), ['run_id'], unique=False)

    op.create_table('ai_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=8), nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('state_reason', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['extraction_issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_proposals_issue_id'), ['issue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_proposals_issue_id'))

    op.drop_table('ai_proposals')
    with op.batch_alter_table('extraction_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_issues_run_id'))

    op.drop_table('extraction_issues')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_project_id'))
        batch_op.drop_index(batch_op.f('ix_ai_usage_at'))

    op.drop_table('ai_usage')
    with op.batch_alter_table('result_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_result_cache_document_sha256'))

    op.drop_table('result_cache')
    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_runs_project_id'))

    op.drop_table('extraction_runs')
    # ### end Alembic commands ###
