"""compliance knowledge base and audit

Revision ID: c831568dbcbb
Revises: c3a8d1e6f2b0
Create Date: 2026-09-14 13:39:52.030975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c831568dbcbb'
down_revision: Union[str, Sequence[str], None] = 'c3a8d1e6f2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=True),
    sa.Column('workbook_hash', sa.String(length=64), nullable=True),
    sa.Column('workbook_built', sa.String(length=32), nullable=True),
    sa.Column('files_discovered', sa.Integer(), nullable=False),
    sa.Column('files_imported', sa.Integer(), nullable=False),
    sa.Column('files_unchanged', sa.Integer(), nullable=False),
    sa.Column('files_failed', sa.Integer(), nullable=False),
    sa.Column('files_skipped', sa.Integer(), nullable=False),
    sa.Column('records_added', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_inactive', sa.Integer(), nullable=False),
    sa.Column('records_flagged', sa.Integer(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['started_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_equivalences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_requirement_id', sa.String(length=16), nullable=False),
    sa.Column('equivalent_requirement_id', sa.String(length=16), nullable=False),
    sa.Column('similarity', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('proposal', sa.String(length=128), nullable=True),
    sa.Column('engineer_validation_status', sa.String(length=16), nullable=False),
    sa.Column('validated_by_id', sa.Integer(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('applicability_conditions', sa.Text(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['knowledge_imports.id'], ),
    sa.ForeignKeyConstraint(['validated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_requirement_id', 'equivalent_requirement_id', name='uq_knowledge_equivalence')
    )
    with op.batch_alter_table('knowledge_equivalences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_equivalences_engineer_validation_status'), ['engineer_validation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_equivalences_equivalent_requirement_id'), ['equivalent_requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_equivalences_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_equivalences_source_requirement_id'), ['source_requirement_id'], unique=False)

    op.create_table('knowledge_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relative_path', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('sha1', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('mtime', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('last_import_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_import_id'], ['knowledge_imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relative_path')
    )
    op.create_table('knowledge_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=128), nullable=False),
    sa.Column('record_id', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['knowledge_imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_issues_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_issues_issue_type'), ['issue_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_issues_record_id'), ['record_id'], unique=False)

    op.create_table('knowledge_requirements',
    sa.Column('requirement_id', sa.String(length=16), nullable=False),
    sa.Column('system', sa.String(length=48), nullable=True),
    sa.Column('subsystem', sa.String(length=64), nullable=True),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('exact_requirement_text', sa.Text(), nullable=False),
    sa.Column('normalized_requirement_text', sa.Text(), nullable=False),
    sa.Column('requirement_hash', sa.String(length=32), nullable=False),
    sa.Column('merge_review_status', sa.String(length=64), nullable=True),
    sa.Column('technical_variant', sa.Text(), nullable=True),
    sa.Column('numbers', sa.Text(), nullable=True),
    sa.Column('n_sources', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['knowledge_imports.id'], ),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    with op.batch_alter_table('knowledge_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_requirements_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_requirements_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_requirements_requirement_hash'), ['requirement_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_requirements_system'), ['system'], unique=False)

    op.create_table('knowledge_sources',
    sa.Column('source_id', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('duplicate_copies', sa.Text(), nullable=True),
    sa.Column('project', sa.String(length=255), nullable=True),
    sa.Column('job_number', sa.String(length=32), nullable=True),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('system', sa.String(length=48), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('specification_family', sa.String(length=64), nullable=True),
    sa.Column('section_numbers', sa.String(length=255), nullable=True),
    sa.Column('document_revision', sa.String(length=32), nullable=True),
    sa.Column('document_date', sa.String(length=64), nullable=True),
    sa.Column('document_review_status', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=64), nullable=True),
    sa.Column('source_review_status', sa.Text(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['knowledge_imports.id'], ),
    sa.PrimaryKeyConstraint('source_id')
    )
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_sources_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_job_number'), ['job_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_manufacturer'), ['manufacturer'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_specification_family'), ['specification_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_system'), ['system'], unique=False)

    op.create_table('compliance_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('clause_id', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('spec_sha256', sa.String(length=64), nullable=True),
    sa.Column('boq_hash', sa.String(length=64), nullable=True),
    sa.Column('scope_hash', sa.String(length=64), nullable=True),
    sa.Column('knowledge_import_id', sa.Integer(), nullable=True),
    sa.Column('knowledge_record_ids', sa.Text(), nullable=True),
    sa.Column('previous_response', sa.Text(), nullable=True),
    sa.Column('current_response', sa.Text(), nullable=True),
    sa.Column('previous_status', sa.String(length=32), nullable=True),
    sa.Column('current_status', sa.String(length=32), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('ai_prompt_version', sa.String(length=48), nullable=True),
    sa.Column('ai_usage', sa.JSON(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['compliance_statements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('compliance_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compliance_audit_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_audit_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_compliance_audit_statement_id'), ['statement_id'], unique=False)

    op.create_table('knowledge_mappings',
    sa.Column('mapping_id', sa.String(length=16), nullable=False),
    sa.Column('requirement_id', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=16), nullable=False),
    sa.Column('specification_family', sa.String(length=64), nullable=True),
    sa.Column('specification_title', sa.String(length=255), nullable=True),
    sa.Column('specification_edition', sa.String(length=64), nullable=True),
    sa.Column('section_number', sa.String(length=32), nullable=True),
    sa.Column('clause_number', sa.String(length=32), nullable=True),
    sa.Column('clause_label', sa.String(length=32), nullable=True),
    sa.Column('heading_context', sa.Text(), nullable=True),
    sa.Column('original_requirement_text', sa.Text(), nullable=True),
    sa.Column('pdf_page', sa.String(length=16), nullable=True),
    sa.Column('printed_page', sa.String(length=16), nullable=True),
    sa.Column('extraction_method', sa.String(length=24), nullable=True),
    sa.Column('pairing_confidence', sa.String(length=16), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['knowledge_imports.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['knowledge_requirements.requirement_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.source_id'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    with op.batch_alter_table('knowledge_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_mappings_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_mappings_clause_number'), ['clause_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_mappings_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_mappings_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_mappings_section_number'), ['section_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_mappings_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_mappings_specification_edition'), ['specification_edition'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_mappings_specification_family'), ['specification_family'], unique=False)

    op.create_table('knowledge_responses',
    sa.Column('response_id', sa.String(length=16), nullable=False),
    sa.Column('requirement_id', sa.String(length=16), nullable=False),
    sa.Column('system', sa.String(length=48), nullable=True),
    sa.Column('manufacturer', sa.String(length=64), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('applicable_models', sa.Text(), nullable=True),
    sa.Column('scope_conditions', sa.Text(), nullable=True),
    sa.Column('responsible_party', sa.String(length=128), nullable=True),
    sa.Column('historical_response', sa.Text(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('historical_compliance_status', sa.String(length=48), nullable=True),
    sa.Column('cited_references', sa.Text(), nullable=True),
    sa.Column('review_flag', sa.Text(), nullable=True),
    sa.Column('specification_families', sa.String(length=255), nullable=True),
    sa.Column('n_sources', sa.Integer(), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('autofill_eligibility', sa.String(length=16), nullable=False),
    sa.Column('eligibility_reasons', sa.Text(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['knowledge_imports.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['knowledge_requirements.requirement_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    with op.batch_alter_table('knowledge_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_responses_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_responses_autofill_eligibility'), ['autofill_eligibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_responses_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_responses_historical_compliance_status'), ['historical_compliance_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_responses_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_responses_manufacturer'), ['manufacturer'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_responses_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_responses_superseded'), ['superseded'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_responses_system'), ['system'], unique=False)

    op.create_table('knowledge_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['knowledge_responses.response_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_models_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_models_response_id'), ['response_id'], unique=False)

    op.create_table('knowledge_response_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.String(length=16), nullable=False),
    sa.Column('mapping_id', sa.String(length=16), nullable=True),
    sa.Column('source_id', sa.String(length=16), nullable=False),
    sa.Column('pdf_page', sa.String(length=16), nullable=True),
    sa.Column('historical_review_status', sa.Text(), nullable=True),
    sa.Column('consultant_comment', sa.Text(), nullable=True),
    sa.Column('superseded_status', sa.Text(), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['knowledge_imports.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['knowledge_responses.response_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_response_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_response_sources_import_id'), ['import_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_response_sources_mapping_id'), ['mapping_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_response_sources_response_id'), ['response_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_response_sources_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_response_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_response_sources_source_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_response_sources_response_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_response_sources_mapping_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_response_sources_import_id'))

    op.drop_table('knowledge_response_sources')
    with op.batch_alter_table('knowledge_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_models_response_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_models_model'))

    op.drop_table('knowledge_models')
    with op.batch_alter_table('knowledge_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_responses_system'))
        batch_op.drop_index(batch_op.f('ix_knowledge_responses_superseded'))
        batch_op.drop_index(batch_op.f('ix_knowledge_responses_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_responses_manufacturer'))
        batch_op.drop_index(batch_op.f('ix_knowledge_responses_import_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_responses_historical_compliance_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_responses_brand'))
        batch_op.drop_index(batch_op.f('ix_knowledge_responses_autofill_eligibility'))
        batch_op.drop_index(batch_op.f('ix_knowledge_responses_active'))

    op.drop_table('knowledge_responses')
    with op.batch_alter_table('knowledge_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_mappings_specification_family'))
        batch_op.drop_index(batch_op.f('ix_knowledge_mappings_specification_edition'))
        batch_op.drop_index(batch_op.f('ix_knowledge_mappings_source_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_mappings_section_number'))
        batch_op.drop_index(batch_op.f('ix_knowledge_mappings_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_mappings_import_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_mappings_clause_number'))
        batch_op.drop_index(batch_op.f('ix_knowledge_mappings_active'))

    op.drop_table('knowledge_mappings')
    with op.batch_alter_table('compliance_audit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compliance_audit_statement_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_audit_project_id'))
        batch_op.drop_index(batch_op.f('ix_compliance_audit_at'))

    op.drop_table('compliance_audit')
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_system'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_specification_family'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_manufacturer'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_job_number'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_import_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_active'))

    op.drop_table('knowledge_sources')
    with op.batch_alter_table('knowledge_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_requirements_system'))
        batch_op.drop_index(batch_op.f('ix_knowledge_requirements_requirement_hash'))
        batch_op.drop_index(batch_op.f('ix_knowledge_requirements_import_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_requirements_active'))

    op.drop_table('knowledge_requirements')
    with op.batch_alter_table('knowledge_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_issues_record_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_issues_issue_type'))
        batch_op.drop_index(batch_op.f('ix_knowledge_issues_import_id'))

    op.drop_table('knowledge_issues')
    op.drop_table('knowledge_files')
    with op.batch_alter_table('knowledge_equivalences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_equivalences_source_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_equivalences_import_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_equivalences_equivalent_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_equivalences_engineer_validation_status'))

    op.drop_table('knowledge_equivalences')
    op.drop_table('knowledge_imports')
    # ### end Alembic commands ###
