"""boq manufacturer unit remarks and extraction warnings

Also drops `projects.systems`, the comma-joined column that project_systems
replaced, where it still exists: create_all never removed it from databases
built before that change.

Revision ID: f7baca5c0a0a
Revises: 61c335c3ba25
Create Date: 2026-09-11 08:26:14.866543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7baca5c0a0a'
down_revision: Union[str, Sequence[str], None] = '61c335c3ba25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_boq_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))

    project_columns = {c["name"] for c in sa.inspect(op.get_bind()).get_columns("projects")}
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boq_extraction_warnings', sa.JSON(), nullable=True))
        if "systems" in project_columns:
            batch_op.drop_column("systems")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('boq_extraction_warnings')

    with op.batch_alter_table('project_boq_items', schema=None) as batch_op:
        batch_op.drop_column('remarks')
        batch_op.drop_column('unit')
        batch_op.drop_column('manufacturer')

    # ### end Alembic commands ###
